name: Bug Report
description: File a bug report to help us improve Institutionalized
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. Run command '...'
        2. Stage changes with 'git add ...'
        3. Execute 'institutionalized commit'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Institutionalized Version
      description: What version of Institutionalized are you running? (Run `institutionalized version` to check)
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - macOS
        - Linux
        - Windows
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using? (Run `go version` to check)
      placeholder: e.g., go1.24.7 darwin/amd64
    validations:
      required: true

  - type: input
    id: git-version
    attributes:
      label: Git Version
      description: What version of Git are you using? (Run `git --version` to check)
      placeholder: e.g., git version 2.42.0
    validations:
      required: true

  - type: dropdown
    id: ai-provider
    attributes:
      label: AI Provider
      description: Which AI provider were you using when the issue occurred?
      options:
        - OpenAI (ChatGPT)
        - Google Gemini
        - Both configured with fallback
        - None (using --dry-run or similar)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Please share your configuration (run `institutionalized config show` or check `~/.config/institutionalized/config.yaml`). 
        **Important**: Remove any API keys before sharing!
      placeholder: |
        providers:
          priority: openai
          openai:
            enabled: true
            model: gpt-3.5-turbo
          gemini:
            enabled: false
        # ... other config
      render: yaml

  - type: textarea
    id: command-output
    attributes:
      label: Command Output
      description: |
        Please paste the full command output, including any error messages.
        **Important**: Remove any API keys or sensitive information!
      placeholder: Paste the command output here...
      render: shell

  - type: textarea
    id: git-status
    attributes:
      label: Git Repository State
      description: |
        What was the state of your git repository when the issue occurred?
        Please include output from relevant git commands.
      placeholder: |
        # git status
        # git diff --cached
        # Any other relevant git information
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. This could include:
        - Screenshots or logs
        - Network conditions (if API-related)
        - Any workarounds you've found
        - Related issues or discussions

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting this issue.
      options:
        - label: I have searched existing issues to make sure this hasn't been reported before
          required: true
        - label: I have removed any sensitive information (API keys, personal data) from this report
          required: true
        - label: I can reproduce this issue consistently
          required: false
        - label: I have tried the latest version of Institutionalized
          required: false